### ISSUE TITLE
HStore issue while upgrading NpgSql from 2.2.5 to 4.1.3.1, FluentNHibernate from 0.2.0.1 to 2.1.2, NHibernate from 4.0.3.4000 to 5.3.0

### ISSUE THREAD

**Issue by riyazahmedm** [FluentNHibernate/fluent-nhibernate#460]
**Issue**

HStore values are not able to read while upgrading NpgSql from 2.2.5 to 4.1.3.1
Please refer the attached zip file which contains ,

1. step for reproducing the issue (NpgSql 2_2_5 to 4_1_3_1 issue.txt)
2. Script for creating DB ( SampleScriptForHstore.txt)
3. Zip file contains sample application for reading Hstore value using NpgSql 2.2.5 and 4.1.3.1
    a) In 4.1.3.1, Getting as Dictionary'2 [String,string] instead of getting value while opening session and reading table
    b) Tried to change, Model property (HStore) from string to Dictionary<string,string> and getting below exception
    
Additional Questions

Question :
  1. What is the solution for reading value , what would be the impact?
  2.  what is the recommended steps to use it as string so no code changes required?
  3. Already product is released to the market with interface method containing Hstore as string, Interface cannot be changed so  all to be recreated. code change and test effort would be more.

4.  Already released with 2.2.5 for same product binaries are used in another product that may still continue to use with 2.2.5 only, In this case how to fix the issue?

         NHibernate.ADOException

HResult=0x80131600
Message=Could not cast the value in field col_1_0_ of type Dictionary2 to the Type SerializableType. Please check to make sure that the mapping is correct and that your DataProvider supports this Data Type. Source=NHibernate StackTrace: at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name) at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String[] names, ISessionImplementor session, Object owner) at NHibernate.Loader.Hql.QueryLoader.GetResultRow(Object[] row, IDataReader rs, ISessionImplementor session) at NHibernate.Loader.Hql.QueryLoader.GetResultColumnOrRow(Object[] row, IResultTransformer resultTransformer, IDataReader rs, ISessionImplementor session) at NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters) at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet1 querySpaces, IType[] resultTypes)
at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
at NHibernate.Impl.AbstractQueryImpl2.List()
at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
at Remotion.Linq.QueryableBase1.GetEnumerator() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at WpfApp2.MainWindow.GetAllItems() in C:\Users\source\repos\NpgSql Issue\Sample work with Npgsql4_1_3_1\WpfApp2\MainWindow.xaml.cs:line 128
at WpfApp2.MainWindow..ctor() in C:\Users\source\repos\NpgSql Issue\Sample work with Npgsql4_1_3_1\WpfApp2\MainWindow.xaml.cs:line 29
Inner Exception 1:
InvalidCastException: GetBytes() not supported for type col_1_0_

 **Further technical details**

Npgsql version: 4.13.1
PostgreSQL version: 11.6
Operating system: Windows 10 x64
Hstore Version : 1.5

First tried only to update NPGSQL from 2.2.5 to 4.1.3.1 and we got the issue,
Then tried to update FluentNHibernate from 0.2.0.1 to 2.1.2 and NHibernate from 4.0.3.4000 to 5.3.0 in order to resolve the issue, but still not able to resolve.

Please Help.

find the code along with two projects below.

**Comment by riyazahmedm** [comment]
raised same issue by another user.

**Comment by riyazahmedm** [comment]
raised same issue by another user.

**Comment by riyazahmedm** [comment]
raised same issue by another user.

**Comment by riyazahmedm** [comment]
raised same issue by another user.

**Comment by riyazahmedm** [comment]
raised same issue by another user.
